### ISSUE TITLE
Just in case you're curious, I'm the author or the reddit post (n/t)

### ISSUE THREAD

**Issue by garoto** [NaiveInvestigator/save-playlist#1]

**Comment by NaiveInvestigator** [comment]
OMG! I am honored to meet u sire! You shall be in my hall of fame lmao. Will also add u in the readme.

P.S: I hope you're not trolling loll

**Comment by garoto** [comment]
lol, no need to modify the readme. It's fine.

**Comment by NaiveInvestigator** [comment]
Too late lmaoo. Thanks for checking it out tho!
